# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f1df7f3836949be6eb024aa72a28c86b865cd78a6b95c97bb3b9735d94eafa2966b83173f277ab6afa59bdd3a900c6b7e6c3244e389cbe9eabe9f41433a0d9

test:
  secret_key_base: 8f3f452107e894958105b202680084dc4699468f0c608ebd007987d459097c8f6eb8723e52237a82e3a3ecdc42445784ced985d8c3bd2a2fd00fe62f5cbec388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
